spring.application.name=ai_interview_backend
# PostgreSQL Connection (Apne database ka naam, username aur password yahan daal)
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.xlxrtkbzwoxmjfjwtdet
spring.datasource.password=MyAiInterviewApp
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (Tables apne aap create ho jayengi)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

gemini.api.key=YOUR_API_KEY_HERE